Import necessary library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [1]:
from sklearn.datasets import make_regression
X ,y =make_regression(n_samples=2000,random_state=1)

In [2]:
X

array([[ 1.24656308, -0.00262717,  1.16177117, ..., -0.14381404,
         1.04897789,  0.36642707],
       [ 1.98789962, -0.74289827,  0.46392306, ..., -0.07953001,
         0.88431814, -0.12744446],
       [-1.18110317, -0.4599301 ,  1.07125243, ...,  0.41026575,
         0.75133724,  0.39310924],
       ...,
       [ 0.10949255, -0.93311559,  1.06941626, ..., -0.15958241,
        -1.09792226,  0.16945106],
       [-0.59682953,  0.91196902,  0.32905821, ..., -0.49513463,
         1.30232475, -0.67180649],
       [ 0.88513231, -0.95744249,  1.24415716, ..., -0.03960346,
        -0.44315668,  1.04897287]])

In [3]:
y

array([-244.6379103 ,  338.19201455, -369.33489019, ...,   89.84615892,
         40.23247176, -113.19250449])

In [4]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X,y,test_size=0.3,random_state=12)

In [5]:
X_train

array([[-0.3102569 , -0.35427619,  0.39650492, ...,  1.26959618,
        -0.30150675, -2.26888313],
       [ 1.28044403,  1.73871889,  0.84672379, ..., -0.51392111,
        -1.44702872, -1.61237671],
       [ 0.58455701, -0.18854658,  0.10667214, ...,  0.3039744 ,
        -0.61025316, -1.2003673 ],
       ...,
       [-0.87636515,  2.1606535 ,  0.69440495, ...,  0.68105216,
         0.4741391 , -1.15527546],
       [ 0.8521572 , -0.50782106, -0.47473822, ..., -2.60530035,
         1.69787155, -0.57837416],
       [-0.92166369,  1.42898437,  0.15152283, ...,  1.97076816,
        -2.0457776 , -0.01832535]])

In [6]:
X_test

array([[-2.47913336e+00, -1.32941774e+00,  7.55895123e-01, ...,
         4.32523466e-01,  6.55392088e-01, -4.89171664e-01],
       [ 1.21935522e+00,  9.17253872e-01, -6.24653153e-02, ...,
         6.51603617e-01,  3.19617561e-02,  5.35192360e-01],
       [ 1.59296974e+00,  1.29511140e-01,  3.47589377e-01, ...,
         1.87142477e-01,  3.10548285e-02,  9.68582688e-01],
       ...,
       [-1.62038450e-01,  7.36388470e-01,  1.29887994e+00, ...,
         1.34411245e+00,  9.42955805e-01,  6.33662061e-01],
       [-1.37604633e-03,  7.85995759e-01,  8.75557342e-02, ...,
         7.93833204e-01, -2.16655900e+00, -1.92740972e+00],
       [ 1.92506088e+00,  1.44194971e+00,  1.00439787e+00, ...,
         4.27048308e-01,  2.08982884e-01, -1.65906685e-01]])

In [8]:
from sklearn.ensemble import AdaBoostRegressor
classifier =AdaBoostRegressor()
classifier.fit(X_train ,y_train)
y_pred =classifier.predict(X_test)
y_pred

array([-5.87332532e+01, -1.88437079e+02,  3.17611873e+02, -1.24581396e+02,
        1.91836928e+02,  9.22488829e+01,  8.32273182e+01,  6.56844204e+01,
       -5.98318024e+01,  2.58257045e+02, -8.14918748e+01, -1.30935198e+01,
        1.15810407e+02,  7.71555155e+01, -6.92389161e+01,  7.39129851e+01,
        1.40338454e+02, -8.97657968e+01, -7.77941160e+01, -2.08445508e+02,
       -1.81232813e+01,  2.53718724e+02,  5.09459617e+01,  7.40800609e+01,
        1.03898585e+02,  1.53045039e+02,  3.48614365e+01,  1.48043815e+01,
        8.22162125e+01, -2.36006741e+02, -4.99362568e+01,  8.94147711e+01,
        2.01256134e+01,  2.98980751e+02,  3.34942498e+01, -9.23263181e+01,
        1.03895724e+02,  1.07130803e+02,  1.96317472e+01, -1.79255668e+02,
        2.63988231e+02,  1.15810407e+02, -5.98318024e+01,  1.16970052e+02,
        1.20981596e+02,  1.29502422e+01,  1.70001258e+02, -3.40671372e+01,
        2.95820875e+01,  1.15810407e+02,  2.57526074e+02, -5.70416306e+01,
       -1.30935198e+01, -

In [9]:
from sklearn.metrics import r2_score
print(r2_score(y_test ,y_pred))

0.7526831001929267


hyperparameter tunning

In [11]:
from sklearn.model_selection import GridSearchCV
param_grid ={"n_estimators":[100,150,200,250,300],
            "learning_rate":[0.001,0.005,0.1,1,1.5,2],
            "loss":["linear",'square','exponentia']}
ada =AdaBoostRegressor()

In [12]:
clf =GridSearchCV(estimator=ada ,param_grid=param_grid ,cv =5,verbose=3)

In [13]:
clf.fit(X_train ,y_train)

Fitting 5 folds for each of 90 candidates, totalling 450 fits
[CV 1/5] END learning_rate=0.001, loss=linear, n_estimators=100;, score=0.509 total time=   4.1s
[CV 2/5] END learning_rate=0.001, loss=linear, n_estimators=100;, score=0.531 total time=   4.1s
[CV 3/5] END learning_rate=0.001, loss=linear, n_estimators=100;, score=0.544 total time=   4.1s
[CV 4/5] END learning_rate=0.001, loss=linear, n_estimators=100;, score=0.415 total time=   4.1s
[CV 5/5] END learning_rate=0.001, loss=linear, n_estimators=100;, score=0.517 total time=   4.1s
[CV 1/5] END learning_rate=0.001, loss=linear, n_estimators=150;, score=0.507 total time=   6.1s
[CV 2/5] END learning_rate=0.001, loss=linear, n_estimators=150;, score=0.542 total time=   6.2s
[CV 3/5] END learning_rate=0.001, loss=linear, n_estimators=150;, score=0.545 total time=   6.1s
[CV 4/5] END learning_rate=0.001, loss=linear, n_estimators=150;, score=0.418 total time=   6.1s
[CV 5/5] END learning_rate=0.001, loss=linear, n_estimators=150;,

/opt/conda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
150 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
150 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py", line 124, in fit
    self._validate_params()
  File "/opt/conda/lib/python3.10/site-packages/sklearn/base.py", line 570, in _validate_params
    validate_parameter_constraints(
  File "/opt/conda/lib/python3.10/site-packages/s

GridSearchCV(cv=5, estimator=AdaBoostRegressor(),
             param_grid={'learning_rate': [0.001, 0.005, 0.1, 1, 1.5, 2],
                         'loss': ['linear', 'square', 'exponentia'],
                         'n_estimators': [100, 150, 200, 250, 300]},
             verbose=3)

In [14]:
clf.best_estimator_

AdaBoostRegressor(learning_rate=1.5, loss='square', n_estimators=300)

In [15]:
clf.best_score_

0.8480457473127408